# Generated by Django 4.2.2 on 2024-11-15 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="где нужно выполнять привычку",
                        max_length=100,
                        verbose_name="место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="выберите дату и время начала",
                        verbose_name="начало выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text="опишите действие, которое нужно сделать",
                        verbose_name="что нужно сделать",
                    ),
                ),
                (
                    "pleasant_habit_sign",
                    models.BooleanField(
                        default=False,
                        help_text="является ли привычка приятной",
                        verbose_name="признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.SmallIntegerField(
                        default=1,
                        help_text="сколько раз в неделю: от 1 до 7",
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="опишите награду за выполнение привычки",
                        max_length=150,
                        null=True,
                        verbose_name="награда за выполнение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        help_text="укажите как долго нужно выполнять привычку",
                        verbose_name="продолжительность выполнения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="опубликовать привычку",
                        verbose_name="признак публикации",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
